// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxZh_7sAwrrgWkoAkC2i6L6rF_SvpE7HE',
    appId: '1:1047114728439:web:209423218bc750b41424f2',
    messagingSenderId: '1047114728439',
    projectId: 'ecommerceapp1',
    authDomain: 'ecommerceapp1.firebaseapp.com',
    storageBucket: 'ecommerceapp1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABWmh8ptckjZDvHGDBqzALt9LYjZqRexA',
    appId: '1:1047114728439:android:5c7b7fb1cb5c85851424f2',
    messagingSenderId: '1047114728439',
    projectId: 'ecommerceapp1',
    storageBucket: 'ecommerceapp1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEtHaGpbcU11Cdw5iHpiOIXUsVabaPn80',
    appId: '1:1047114728439:ios:4d33c3604e4db92d1424f2',
    messagingSenderId: '1047114728439',
    projectId: 'ecommerceapp1',
    storageBucket: 'ecommerceapp1.appspot.com',
    iosClientId: '1047114728439-837mjt645b3jtjatthsqtohd1s7pq760.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
